services:
  - type: web
    name: ttn-website
    env: node
    plan: starter
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        sync: false
      - key: PGUSER
        sync: false