services:
  - type: web
    name: ttn-website
    env: node
    plan: starter
    buildCommand: npm install --legacy-peer-deps && node render-build.js
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        sync: false
      - key: PGUSER
        sync: false